apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka2
  name: kafka2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: kafka2
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: LISTENER_DOCKER_INTERNAL://kafka2:19093,LISTENER_DOCKER_EXTERNAL://127.0.0.1:9093
            - name: KAFKA_BROKER_ID
              value: "2"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: LISTENER_DOCKER_INTERNAL
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
            - name: KAFKA_LOG4J_LOGGERS
              value: kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zoo1:2181
          image: confluentinc/cp-kafka:6.2.1
          name: kafka2
          ports:
            - containerPort: 9093
          resources: {}
      hostname: kafka2
      restartPolicy: Always
status: {}
